// <auto-generated />
using System;
using GestionTareas.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionTareas.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924024707_CrearTablaProyecto")]
    partial class CrearTablaProyecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("GestionTareas.Api.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("proy_codigo")
                        .HasComment("Código único del proyecto, generado automáticamente de forma secuencial por la base de datos.");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("proy_descripcion")
                        .HasComment("Descripción detallada del alcance u objetivo del proyecto. Campo opcional.");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proy_estado")
                        .HasComment("Estado actual del proyecto. Valores permitidos: PLANIFICADO, EN_CURSO, PAUSADO, FINALIZADO, CANCELADO.");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proy_fecha_actualizacion")
                        .HasComment("Fecha y hora de la última modificación del proyecto. Es nula mientras no haya sido editado.");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proy_fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Fecha y hora en que se registró el proyecto en el sistema. Se asigna automáticamente al crearlo.");

                    b.Property<DateOnly>("FechaFinPrevista")
                        .HasColumnType("date")
                        .HasColumnName("proy_fecha_fin_prevista")
                        .HasComment("Fecha estimada de finalización del proyecto. Debe ser mayor o igual a la fecha de inicio.");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("proy_fecha_inicio")
                        .HasComment("Fecha en la que inicia la ejecución del proyecto.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("proy_nombre")
                        .HasComment("Nombre del proyecto. Se utiliza para identificarlo en la interfaz y como criterio de búsqueda por coincidencia parcial.");

                    b.HasKey("Id")
                        .HasName("pk_proyecto");

                    b.ToTable("proyecto", null, t =>
                        {
                            t.HasComment("Representa una iniciativa de trabajo con un periodo de ejecución definido y un estado, que agrupa un conjunto de tareas.");

                            t.HasCheckConstraint("ck_proyecto_fechas", "proy_fecha_fin_prevista >= proy_fecha_inicio");

                            t.HasCheckConstraint("ckc_proy_estado_proyecto", "proy_estado IN ('PLANIFICADO', 'EN_CURSO', 'PAUSADO', 'FINALIZADO', 'CANCELADO')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
